language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
sudo: required
services:
  - docker
script:
  - mvn package docker:build -DskipTests
  - docker-compose up -d
  - sleep 60
  - mvn test