language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
script:
- mvn package docker:build -DskipTests
- docker-compose up -d
- sleep 30
- mvn test
addons:
  sauce_connect: true
env:
  global:
  - secure: sqJ5q+3kjBw4HIret0ZOikHojNR149GVo7PsFj9ZLanku4+KVeTi65LgYkEuCxmfOszSxd/RDXkpg39ExZDe4ub0tABtpXPjrCKR5DqVp4xOoHwU8fzVXnVCfgw6ra91Zk6K4UsrOcSx5wdnlbeTsPSYsvZnBf+IaamWJHM55FS2KfiMNi4qc8inqfYHF+dvB7tM8I5IOlteUFk4xYT8AEokMpIqt3L7d3gFOGbr8wUC4K2pEm56pT5b66hglBX9MZr2OGQgAglzpF0VZhFp6xs/zsnqj6VIj7UXTECGh4NDkC3nDh8IPRtg3/gUB4CVe3bfhem2zwWwOxi1689q/Ohi/G7qFJ7UKnznCT3uaW4hKUCqGiduq6DMN3V7P2TyqBIoLWEMn915QWjxWRiXXnUB15zvm3EO1dxocPOQ6gelWsB1vLKKi9qNzGFN6cbGsKo36EGzIdD9dYM6LyOVeDyHZvIFLz32yQanqvEoeIA2wzthe177z/Pn/jmT0LIZ8xpadD7iMcU17LUoXQASPKUB8+EE3sl6RloU8dXofkZHdARfxNWmWkk+OSSWoc9hn35w2why/3Urgw2jh/EcpFdYeSFGjuHMPVQcdkXcNkNQqqOHS8FqoqhtVbSn4+Jz7pF/oopth+CwXhcuqQ8UhYDlzP/ccfj6iMSqZ6exPVE=
  - secure: cxMjWbA07W/SpWOoXIf9lrJiBKPaniILt5pptfKANqaPrlDbJA6Z7gvF0GANFX5Sk+xZtDCsM0wg4HQNrencvjOpBFOK1G1ktl0IIhdOxegLkXTb5BnKXP8YKX9wb94LdtHfSFBVq3oCKy8Dpqtqs2ZucD4ymuTcptYdV86RLOXpOPGZC8H+9eJfLQjgCXfxcFZ8JpacT+8qard4baBhjhY+e8KhW/EsPNRKng5oBkfpHw8uf3B5XDr5aassk5cz6F64OWfAYnNc6KCccUiHovlVTOVLp/bL8iK5bH3sHTIjfrmZi52kXOzq2A6cHqNiXjySz84bORzB2s4hGZaO9kBgvGqiPmPX5x92XEiFIo3LHqBTi2HADttC63jkmD5PL4AQQlHopzGpNH/KFv/BgtTgbCUvVgFpQTZFxzNZHVdMMlYs9ZnXT7BLWKepa97KQcAOnuN6ITjpP1RkTYh44TGmmHiPyjfadzcvG1w40hbw+y7179EdGtxVemLcmaIcOsE18Jz138mmHFgLHbQ80Nb/TAqh/u3qdA2H312WsawYTS/eMTyVqFa9spdhAeNkZ/vr7Usp7cJoDFTcjSJYyg8jmarD7kslAh/vVhx0Ylht0o/5g49j7iWQ5LwNcElPn2yIz52lH/K0OGp5ShX4aLx5V8Tox01/WxWE4KfV6Lk=
